# Generated by Django 5.1.8 on 2025-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0053_annotation_bulk_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFileCacheModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=255)),
                ("task_id", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_file_cache",
            },
        ),
    ]
